version: '3'
services:
  web:
      image: webdevops/php-apache-dev:8.1
      container_name: web
      restart: always
      user: application
      environment:
        - WEB_ALIAS_DOMAIN=local.magento.com
        - WEB_DOCUMENT_ROOT=/app/pub
        - PHP_DATE_TIMEZONE=EST
        - PHP_DISPLAY_ERRORS=1
        - PHP_MEMORY_LIMIT=2048M
        - PHP_MAX_EXECUTION_TIME=300
        - PHP_POST_MAX_SIZE=500M
        - PHP_UPLOAD_MAX_FILESIZE=1024M
      volumes:
        - .:/app:cached
      ports:
        - "8081:80"
        - "443:443"
        - "32823:22"
      links:
        - mysql
        - elasticsearch
  mysql:
      image: mariadb:10.6
      container_name: mysql
      restart: always
      ports:
        - "3306:3306"
      environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_DATABASE=magento
      volumes:
        - db-data:/var/lib/mysql
  phpmyadmin:
      container_name: phpmyadmin
      restart: always
      image: phpmyadmin/phpmyadmin:latest
      environment:
        - MYSQL_ROOT_PASSWORD=root
        - PMA_USER=root
        - PMA_PASSWORD=root
      ports:
        - "8080:80"
      links:
        - mysql:db
      depends_on:
        - mysql
  elasticsearch:
      image: elasticsearch:7.9.3
      environment:
        - node.name=magento01
        - cluster.name=magento-cluster
        - bootstrap.memory_lock=true
        - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        - discovery.type=single-node
      ulimits:
        memlock:
          soft: -1
          hard: -1
      volumes:
        - es-data:/usr/share/elasticsearch/data
  kibana:
    image: docker.elastic.co/kibana/kibana:7.9.3
    container_name: kibana
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
 
volumes:
   db-data:
       external: false
   es-data:
       external: false